"""Add account

Revision ID: 258efe07bde6
Revises: 
Create Date: 2019-10-27 11:52:14.789973

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import insta_backend


# revision identifiers, used by Alembic.
revision = '258efe07bde6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('favourite_color', sa.String(), nullable=False),
    sa.Column('favourite_food', sa.String(), nullable=False),
    sa.Column('favourite_song', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_created'), 'user', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_created'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
