"""Added constraints for col status in user

Revision ID: fb92d381ab6a
Revises: 180046a31cb3
Create Date: 2019-11-02 23:15:43.686061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb92d381ab6a'
down_revision = '180046a31cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=sa.String(length=30),
               nullable=False)
    op.create_index(op.f('ix_user_status'), 'user', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_status'), table_name='user')
    op.alter_column('user', 'status',
               existing_type=sa.String(length=30),
               nullable=True)
    # ### end Alembic commands ###
